CREATE TABLE [dbo].[Product]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY (1,1),
	[Description] VARCHAR(200) NOT NULL,
	[Price] NUMERIC(17,2) NOT NULL,
	[UrlImg] VARCHAR(8000) NOT NULL,
	[CategoryId] INT NOT NULL
)
