CREATE TABLE [dbo].[User]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY (1,1),
	[UserName] VARCHAR(20) NOT NULL,
	[HasPw] VARCHAR(50) NOT NULL,
	[FirstName] VARCHAR(20) NOT NULL,
	[LastName] VARCHAR(20) NOT NULL,
	[Email] VARCHAR(50) NOT NULL,

)
